	tilepal 0, GRAY, BROWN, BROWN, RED, GREEN, GREEN, GRAY, ROOF
	tilepal 0, RED, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GREEN, WATER, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, RED, GREEN, GREEN
	tilepal 0, RED, RED, BROWN, ROOF, ROOF, RED, YELLOW, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED, ROOF
	tilepal 0, RED, BROWN, BROWN, RED, BROWN, GRAY, GRAY, YELLOW
	tilepal 0, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, RED, BROWN, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, WATER, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, BROWN, BROWN, RED, BROWN, GRAY, RED, GRAY
	tilepal 0, WATER, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY
	tilepal 0, BROWN, ROOF, ROOF, RED, BROWN, BROWN, YELLOW, RED
	tilepal 0, RED, YELLOW, YELLOW, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, BROWN, BROWN, BROWN, BROWN, ROOF, BROWN, BROWN, BROWN
	tilepal 0, BROWN, YELLOW, YELLOW