	tilepal 0, GRAY, BROWN, BROWN, RED, GREEN, GREEN, YELLOW, YELLOW
	tilepal 0, RED, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GRAY, WATER, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, GREEN, GREEN
	tilepal 0, ROOF, ROOF, BROWN, BROWN, BROWN, GRAY, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, ROOF, ROOF, ROOF, ROOF, YELLOW, ROOF, ROOF, WATER
	tilepal 0, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, ROOF, ROOF, ROOF, ROOF, BROWN, ROOF, ROOF, ROOF
	tilepal 0, ROOF, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, ROOF, ROOF, RED, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN