	tilepal 0, GRAY, GRAY, RED, WATER, WATER, WATER, GRAY, RED
	tilepal 0, RED, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, WATER, WATER, WATER, GRAY, RED
	tilepal 0, RED, GRAY, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, YELLOW, YELLOW, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, BROWN, BROWN, YELLOW, YELLOW, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, YELLOW
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY
	tilepal 0, GRAY, WATER, YELLOW, WATER, GRAY, GRAY, GRAY